name: Analyze GitHub Security Findings

on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
      - Dev

permissions:
  contents: read
  security-events: read

jobs:
  analyze-findings:
    name: Analisar Findings de Segurança com TinyLlama
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Remover versões conflitantes do Docker
        run: |
          sudo apt-get remove --purge containerd containerd.io || true
          sudo apt-get update

      - name: Instalar Docker e Docker Compose
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image (caso necessário)
        run: |
          docker-compose -f docker-compose.yml build

      - name: Iniciar Containers
        run: |
          docker-compose -f docker-compose.yml up -d
          sudo docker exec ollama ollama pull tinyllama

      - name: Baixar findings de segurança
        run: |
          mkdir -p findings

          echo "🔍 Baixando Code Scanning..."
          curl -s -H "Authorization: token ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/code-scanning/alerts \
            -o findings/code-scanning.json

          echo "🔐 Baixando Secret Scanning..."
          curl -s -H "Authorization: token ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/secret-scanning/alerts \
            -o findings/secrets.json || echo "Erro ao baixar Secret Scanning"

          echo "📦 Baixando Dependabot..."
          curl -s -H "Authorization: token ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dependabot/alerts \
            -o findings/dependabot.json || echo "Erro ao baixar Dependabot"

      - name: Analisar cada finding com TinyLlama
        run: |
          analyze_findings() {
            local type="$1"
            local file="findings/${type}.json"

            echo "🔎 Analisando findings de ${type}..."
            count=$(jq length "$file")

            if [ "$count" -eq 0 ]; then
              echo "✅ Nenhum finding de ${type} encontrado."
              return
            fi

            for i in $(seq 0 $(($count - 1))); do
              finding=$(jq -r ".[$i]" "$file")

              number=$(echo "$finding" | jq -r '.number')
              created_at=$(echo "$finding" | jq -r '.created_at')
              updated_at=$(echo "$finding" | jq -r '.updated_at')
              description=$(echo "$finding" | jq -r '.rule.description')
              severity=$(echo "$finding" | jq -r '.rule.severity')
              location_path=$(echo "$finding" | jq -r '.most_recent_instance.location.path')
              location_line=$(echo "$finding" | jq -r '.most_recent_instance.location.start_line')
              message_text=$(echo "$finding" | jq -r '.most_recent_instance.message.text')
              html_url=$(echo "$finding" | jq -r '.html_url')
              help_uri=$(echo "$finding" | jq -r '.rule.help_uri')

              formatted_prompt="Analisando vulnerabilidade encontrada no repositório: BsidesApresenta-o

              ID do Finding foi $number
              Data de Criação foi  $created_at
              Data de Atualização foi $updated_at
              Descrição do Finding foi $description
              Severidade foi $severity
              Caminho foi $location_path
              Linha foi $location_line
              Mensagem foi $message_text
              avalie se foi falso positivo ou nao
              Consulte a documentação para mais informações caso queira $help_uri
              Link para o finding no GitHub foi 
              $html_url
              "

              echo "🔍 Enviando prompt para o TinyLlama: $formatted_prompt"

              response=$(curl -s -X POST http://localhost:11399/api/generate \
                -H "Content-Type: application/json" \
                -d "{\"model\": \"tinyllama\", \"stream\": false, \"prompt\": \"$formatted_prompt\"}")

              result=$(echo "$response" | jq -r '.response // .error')

              echo "Resposta da IA: $response"

              if [ "$result" == "null" ]; then
                echo "⚠️ Erro na resposta da IA: $response"
              else
                echo "🧠 Resultado da IA: $result"
              fi
            done
          }

          analyze_findings "code-scanning"
          echo "🧪 Tentando analisar secrets.json..."
          ( analyze_findings "secrets" ) || echo "⚠️ Erro ao analisar findings de secrets ou arquivo inválido."

          echo "🧪 Tentando analisar dependabot.json..."
          ( analyze_findings "dependabot" ) || echo "⚠️ Erro ao analisar findings de dependabot ou arquivo inválido."

      - name: Parar ambiente TinyLlama
        run: |
          docker stop ollama && docker rm ollama
