name: Security Scan

on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
      - Dev

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit.json || true

      - name: Check Bandit JSON output
        run: cat bandit.json

      - name: Run Bandit to SARIF conversion
        run: |
          python scripts/bandit_to_sarif.py

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit-results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Garantir que o token é passado corretamente

      - name: Start Django development server
        run: |
          export SECRET_KEY=${{ secrets.secret }}
          python manage.py migrate # Realize as migrações, se necessário
          python manage.py runserver &

      - uses: actions/checkout@v3
      - name: OWASP ZAP Baseline Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-baseline@7cea08522cd386f6c675776d5e4296aecf61f33b
        uses: zaproxy/action-baseline@v0.7.0
        with:
          # Target URL
          target: "http://127.0.0.1:8000"
        continue-on-error: true

      - name: Stop Django development server
        run: |
          pkill -f "python manage.py runserver"

   