name: Security Scan with Trivy

on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
      - Dev

permissions:
  contents: read  # Permissão para acessar o conteúdo do repositório
  security-events: write  # Permissão para enviar eventos de segurança

jobs:
  security:
    name: Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'         # Modo fs (sistema de arquivos)
          scan-ref: '.'           # Escaneia o diretório atual

      - name: Upload Trivy SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
          wait-for-processing: true
